"""empty message

Revision ID: 0877e16db24b
Revises: 631930e5d9c0
Create Date: 2022-02-09 21:12:52.343244

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0877e16db24b'
down_revision = '631930e5d9c0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('car',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=True),
    sa.Column('price', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('features', sa.String(length=250), nullable=True),
    sa.Column('engine', sa.String(length=100), nullable=True),
    sa.Column('technologies', sa.String(length=150), nullable=True),
    sa.Column('wheels', sa.String(length=100), nullable=True),
    sa.Column('safety', sa.String(length=100), nullable=True),
    sa.Column('dimensions', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('fuel_economy', sa.String(length=100), nullable=True),
    sa.Column('accessories', sa.String(length=150), nullable=True),
    sa.Column('user_token', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['user_token'], ['user.token'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('car')
    # ### end Alembic commands ###
