"""empty message

Revision ID: 1d4e046848e5
Revises: 0877e16db24b
Create Date: 2022-02-10 09:25:07.072681

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1d4e046848e5'
down_revision = '0877e16db24b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('car', sa.Column('dimension', sa.String(length=100), nullable=True))
    op.drop_column('car', 'dimensions')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('car', sa.Column('dimensions', sa.NUMERIC(precision=10, scale=2), autoincrement=False, nullable=True))
    op.drop_column('car', 'dimension')
    # ### end Alembic commands ###
